# Site settings

title: Ral Oliver # Title of your site
email: contato@raloliver.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Um homem direcionado, com motivação ampla, tesão pela vida, vontade e muito curioso. Me falta apenas mais tempo pra fazer tudo o que desejo. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raloliver.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     raloliver  # Replace this with your Twitter username
github_username:      raloliver  # Replace this with your GitHub username
linkedin_username:    raloliver  # Replace this with your LinkedIn username
google_plus_username: raloliver  # Replace this with your Google+ username
facebook_username:    raloliver  # Replace this with your Facebook username
youtube_username:     raloliver  # Replace this with your Youtube username

# Build settings
markdown: kramdown
